### ISSUE TITLE
Add docs to install pre-existing build

### ISSUE THREAD

**Issue by shreddd** [llanaproject/psana_jupyter_kernel#1]
It would be useful to have a simple set of instructions to install the existing conda kernel from /global/common/software. 

Could be a small fix to just change the $DIST location and assume an existing build

**Comment by muammar** [comment]
> It would be useful to have a simple set of instructions to install the existing conda kernel from /global/common/software.
> 
> Could be a small fix to just change the $DIST location and assume an existing build

There is an existent conda kernel installed at `/global/common/software` that to be used @NERSC  users would only have to copy the `kernel.json` to their `$HOME/.local/. I think that would solve this issue.

**Comment by muammar** [comment]
@shreddd I have updated the README file https://github.com/llanaproject/psana_jupyter_kernel. Let me know if you think this solves the problem to proceed and close this report.

**Comment by muammar** [comment]
Please feel free to reopen this issue if you think it is not fixed yet.
